### PR TITLE
feat: add ScatterChart component

### PR DESCRIPTION
**Pull request by mbauchet**
**Description**
Adding ScatterChart component with specific tooltip

**Related issue(s)**
#563 

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**How has This been tested?**
Using StoryBook

**Screenshots (if appropriate):**
Capture d’écran 2023-07-22 à 16 25 08

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the related issue section above
- [x] My change requires a change to the documentation. (Managed by Tremor Team)
- [ ] I have added tests to cover my changes
- [x] Check the ["Allow edits from maintainers" option](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) while creating your PR.
- [x] Add refs #XXX or fixes #XXX to the related issue section if your PR refers to or fixes an issue.

### CODE REVIEW

**Comment by christopherkindl** [comment]
Thanks so much, @mbauchet! We will review it asap!

**Comment by christopherkindl** [comment]
Thanks so much @mbauchet for the work so far! Added `opacity` prop, such that overlapping data points become visible.

We will discuss with the team how we should do valueFormatting on the x-Axis. We like your formatting approach you have chosen in the tooltip. Will eventually apply this to the axis as well.

Again, many thanks for the great work! 💙

**Comment by mbauchet** [comment]
Oh thanks for the FAAAST review! ,🚀👌

**Comment by christopherkindl** [comment]
Hi @mbauchet,

we think it makes most sense to only offer one valueFormatting prop and use a dict instead of an array (better DX when only formatting one axis -> e.g. does not require to use two commas when only formatting z-value):

`valueFormatters={{ x: (v) => valuerFormatterX(v), y: (v) => valuerFormatterY(v), z: (v) => valuerFormatterZ(v) }}` 

This means the valueFormatting should apply to both the axis and tooltip. Does this make sense to you?

Happy to hear your opinion and feel free to integrate it!

**Comment by mbauchet** [comment]
Hi @christopherkindl ,

I'm in for X et Y axis! For Z axis, it's a bit different because his value is not always displayed as the tooltip content can be editable.
I think a distinct value formater property for tooltip values only could be great, because as the content is editable we can have strings or number as value (eg France, Albania,...)
Let me know what we can do and I'll integrate it asap

**Comment by christopherkindl** [comment]
Hi @mbauchet,

we decided on the following approach for the first release:

- only one valueFormatting prop with x, y, z (all optional, as a dict)
- In the tooltip always x, y, z values are shown (hence no additional formatting needed there). Also means we wouldn't allow to use additional categories not used for x, y and z (e.g. France)

The reason for that is that this adapts to the tooltip logic we have already in place for other charts. It would be confusing if people only can add additional categories in the scatter chart. But we will follow your tooltip logic in one of the next releases and apply to the other ones as well!

Does this make sense to you?

**Comment by mbauchet** [comment]
New PR #586

**Pull request closed without merging**
