### PR TITLE
feat: progress circle

### LINKED ISSUE #687: [Feature]: <ProgressCircle /> component
### What problem does this feature solve?

Introduction of a new component to visualize progress in new ways as opposed to our data bars.

### What does the proposed API look like?

Component to be coded only using html / svg. **Proportion and size details** can be found in the image below.

Explicit props:

- **value:** number [0-100]
- **size?:** string ["xs", "sm" (default), "md", "lg", "xl"]
- **color?:** string // please use same color mapping logic as in [ProgressBar](https://github.com/tremorlabs/tremor/blob/cbd580a12c5972ef3b1ac5a134e1a8d68d7dd933/src/components/vis-elements/ProgressBar/ProgressBar.tsx#L11)
- **showLabel?:** boolean
- **showAnimation?:** boolean // please use CSS animation (fill up to threshold, same as in ProgressBar)
- **tooltip?:** string // please use same logic as in [Icon](https://www.tremor.so/docs/components/icons)

for `className` prop it should be possible to adjust the size via tailwind heights (e.g. h-10)

ProgressCircle

### PR DESCRIPTION
**Pull request by jzfrank**
**Description**
Add a progress circle component. 

This PR is largely inspired by https://github.com/mfts/gauge-demo 

**Related issue(s)**
https://github.com/tremorlabs/tremor/issues/687

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**How has This been tested?**

storybook

**Screenshots (if appropriate):**

image
Different color

image
Different size 

image
Without label 

image
Tooltip

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the related issue section above
- [x] My change requires a change to the documentation. (Managed by Tremor Team)
- [ ] I have added tests to cover my changes
- [x] Check the ["Allow edits from maintainers" option](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) while creating your PR.
- [x] Add refs #XXX or fixes #XXX to the related issue section if your PR refers to or fixes an issue.
- [x] By contributing to Tremor, you confirm that you have read and agreed to Tremor's [CONTRIBUTING.md](https://github.com/tremorlabs/tremor/blob/main/CONTRIBUTING.md) guideline. You also agree that your contributions will be licensed under the [Apache License 2.0](https://github.com/tremorlabs/tremor/blob/main/License) license.

### CODE REVIEW

**Comment by christopherkindl** [comment]
Hi @jzfrank, many thanks for your work so far! 👍  Changed a few styling things and added `className` prop. 

One thing that is missing is to not show any progress if value is 0:

Screenshot 2023-09-23 at 11 13 05


It's possible that there could be more requirements, as we will thoroughly test this component next week.

**Comment by jzfrank** [comment]
@christopherkindl Thanks for the feedback, improvement and suggestions! I have fixed the zero value display bug. Yep let's have a proper test before publish :)

**Comment by christopherkindl** [comment]
Thanks @jzfrank! I didn't manage to make the values for `viewBox` and `CX/CY/R` dynamic. Currently it is hardcoded with `"0 0 120 120"` for `cx=60` and `cy=60`  and `r=53` for `circumference=332` (2 * Math.PI * 53; // 2 * pi * radius). It's just a weird behaviour, tried it with the variables I left in the comments but does not seem to work

**Comment by christopherkindl** [comment]
Looks solid @jzfrank!

What's missing is a `noDataText` prop which we have used in our charts as well. With this prop, it should be possible to do empty states as follows (empty string provided in the right image):

Frame 2609003

**Comment by jzfrank** [comment]
Hi @christopherkindl, thanks for the feedback! 

I've just done a bit code refactoring and added the `noDataText` prop, which will show when `value` is `undefined`. I've also added a `MiscDemo` for progressCircle storybook, feel free to add more! 

image

Let me know if this is has all necessary behaviors.

**Review by severinlandolt — APPROVED** [review]

**Pull request merged**
