### PR TITLE
feat: Partial donut or pie chart

### LINKED ISSUE #474: Partial donut or pie chart
I can't see there is a way to generate a partial donut/pie chart. I think a donut would be nice to use as a "gauge" where I could give some values and a max value and the donut would only be partially filled based on how many percentage the values cover based on the max value.

### PR DESCRIPTION
**Pull request by gitstart**
## Demo 
Loom Video: https://www.loom.com/share/7fa1765cc095433e90b10558a773da16

 ## Related Issue

Fixes #474 

## What
Add props to the user customize the donuts/pies

## Why
to be possible to set custom angles to this component

# How
Set the props startAngle and percentage as values passed by the user

## Testing

run:
```bash
npm run storybook
```

- Go to ChartElements/DonutChart

- Go to "Custom Size Template" and change the props startAngle

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
Hey @mitrotasios! Could you kindly review this PR, please?

**Comment by mitrotasios** [comment]
Thanks for this, will review after v3 :)

**Comment by gitstart** [comment]
Hello @mitrotasios. Hope you are well.
Since we're already on version 3, could you review this PR?
It would be really interesting if you could review these other two features as well.
#486 #484 
Thank you. :wave:

**Comment by severinlandolt** [comment]
Cf. #474

**Pull request closed without merging**
