### PR TITLE
fix: static and dynamic children

### LINKED ISSUE #686: [Bug]: weird typescript error when mapping SearchSelectItems in SearchSelect component
### Tremor Version

@tremor/react@3.7.2

### Link to minimal reproduction

https://codesandbox.io/p/sandbox/still-voice-q9sxfn?file=%2Fpages%2F_app.tsx%3A7%2C1

### Steps to reproduce

- Setup a NextJS + Tailwind project in Typescript 
- (Ofc) Install tremor labs
- Use SearchSelect component anywhere you like
- Add a SearchSelectItem component inside it
- Now, map over a list of strings to generate some more SearchSelectItem components below the previously created SearchSelectItem component
- And then you'll see a type error like this for the line where you use map
```
Type error: Type 'Element[]' is missing the following properties from type 'ReactElement<any, string | JSXElementConstructor<any>>': type, props, key
```

OR 

Just checkout the above reproduction link and run `npm run build`

### What is expected?

It works without any errors

### What is actually happening?

It throws the error during build process (`npm run build`)

### What browsers are you seeing the problem on?

_No response_

### Any additional comments?

Also, I figured this error only happens when you have the first single SearchSelectItem seperately along AND the rest of the SearchSelectItems through map. Commenting out either one of those fixes the bug — quite weird — but I need to have both of them since currently there is no way to clear the input otherwise. 

If this would take time to figure out and fix... I hope that atleast #681, where I extended the `enableClear` functionality for SearchSelect, could be merged so that I get away by just using the map. Thanks! :)

### PR DESCRIPTION
**Pull request by motinados**
**Description**
The cause of this error is the constraint on the children's type. To resolve it, the type of children has been changed to ReactNode.

**Related issue(s)**
Fixes #686 

**What kind of change does this PR introduce?** (check at least one)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)
- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**How has This been tested?**
jest and storybook

**Screenshots (if appropriate):**

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the related issue section above
- [ ] My change requires a change to the documentation. (Managed by Tremor Team)
- [x] I have added tests to cover my changes
- [x] Check the ["Allow edits from maintainers" option](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) while creating your PR.
- [x] Add refs #XXX or fixes #XXX to the related issue section if your PR refers to or fixes an issue.
- [x] By contributing to Tremor, you confirm that you have read and agreed to Tremor's [CONTRIBUTING.md](https://github.com/tremorlabs/tremor/blob/main/CONTRIBUTING.md) guideline. You also agree that your contributions will be licensed under the [Apache License 2.0](https://github.com/tremorlabs/tremor/blob/main/License) license.

### CODE REVIEW

**Comment by severinlandolt** [comment]
Man, you are as fast as it gets! Was about to fix the tests and got notified: 
CleanShot 2023-11-07 at 21 49 52

**Comment by motinados** [comment]
I will return it to draft for now as there is something of concern.

**Comment by motinados** [comment]
@severinlandolt @mbauchet 
It seemed like it wasn't working on my local Next.js app, but it turned out to be a misunderstanding on my part. Could you please review the pull request?
Thanks,

**Review by mbauchet — APPROVED** [review]

**Review by severinlandolt — APPROVED** [review]

**Comment by severinlandolt** [comment]
Thank you very much, your contributions are highly appreciated @motinados! 🙏

**Comment by severinlandolt** [comment]
Hi @motinados, the mapping is now working fine locally and in my test projects.

There has been one issue with unresolved promises. E.g. if data comes from Tanstack query it will be undefined until the promise is resolved. Resulting in this error:

```console
TypeError: Cannot read properties of null (reading 'props')
at selectutils
at mapIntoArray
at mapIntoArray
at Object.mapChildren [as map]
at 011 selectutils
at updateMemo 
at Object.useMemo
at useMemo
```

CleanShot 2023-11-10 at 17 13 34

mbauchet pointed out, that the problem might be the `constructValueToNameMapping ` function.

Could you take a look at this issue? Feel free to create a new branch from `beta`

**Comment by motinados** [comment]
@severinlandolt @mbauchet 
Thank you for your feedback. However, I am unable to reproduce the issue here. 

I did encounter a similar error when the data retrieved with Tanstack query contains null, but it appears at the value={String(coworker.fullname)} in SearchSelectItem. 

Since undefined until the promise is resolved  filtered out using isValidElement, I believe it should not be a problem. 

Could there be some cache remaining? If you are using a Next.js app, please try deleting the .next folder and testing again.

**Comment by severinlandolt** [comment]
@motinados Heya! One user reported an issue about the children prop. I don't quite understand what is going wrong, because lit looks OK to me actually:

https://github.com/tremorlabs/tremor/issues/859

**Pull request merged**
