### PR TITLE
feat: add scatter chart with basic tooltip and axis value formatters

### PR DESCRIPTION
**Pull request by mbauchet**
**Description**

Add scatter chart component
**Related issue(s)**
#563 

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**How has This been tested?**

**Screenshots (if appropriate):**
Capture d’écran 2023-07-25 à 20 46 32

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the related issue section above
- [x] My change requires a change to the documentation. (Managed by Tremor Team)
- [ ] I have added tests to cover my changes
- [x] Check the ["Allow edits from maintainers" option](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) while creating your PR.
- [x] Add refs #XXX or fixes #XXX to the related issue section if your PR refers to or fixes an issue.

### CODE REVIEW

**Comment by severinlandolt** [comment]
Hi @mbauchet, thank you for your great work, the component looks very good 👍 I just spent some time on the branch, trying to clip the bubbles that overflow the grid area (yellow). But no success using CSS overflow clip/hidden. Also setting margins like `{{top: 0, right: 0, bottom: 0, left: 0,}}` did not work for all cases (i.e.I was setting "magic values" like -59, only working for certain breakpoints)
CleanShot 2023-07-26 at 22 52 42@2x

In any case, if you have an idea how to clip the area like here, that would be awesome, otherwise it's alright.
CleanShot 2023-07-26 at 23 06 13@2x

**Comment by mbauchet** [comment]
I'll check today if I can find something... I'll let you inform

**Comment by mbauchet** [comment]
Didn't find an easy way to accomplish it for now... Except adding padding to X and Y axis to avoid axis values to be hidden, but not entirely convinced by the result...
image

At least, we should add margin on the right side in order to have the same overflowing on each sides
Capture d’écran 2023-07-27 à 08 30 45

**Comment by severinlandolt** [comment]
Thank you for researching, we will handle the margin, thanks!

**Pull request merged**
