### PR TITLE
Refactor css classes with prefix tr

### PR DESCRIPTION
**Pull request by mitrotasios**

### CODE REVIEW

**Comment by OmkarK45** [comment]
Wonder why didn't you go with this option? 
https://tailwindcss.com/docs/configuration#prefix

**Comment by mitrotasios** [comment]
@OmkarK45 we did go with this option, or am I missing something?

**Comment by OmkarK45** [comment]
> @OmkarK45 we did go with this option, or am I missing something?

Oh right, just saw the config. https://github.com/tremorlabs/tremor/blob/238f7ea533ac3954722af0371a3a5bb6b3f59074/tailwind.config.js#LL18C2-L18C19

really clean library this. Will definitely use someday

**Comment by mitrotasios** [comment]
Thanks! Happy coding 🚀

**Pull request merged**
