### PR TITLE
fix(tooltip): set max width for the tooltip

### LINKED ISSUE #454: Bug: long tooltips overflow the screen
If the tooltip text is too long, it overflows the screen and causes a horizontal scroll.

### PR DESCRIPTION
**Pull request by amirhhashemi**
Closes: https://github.com/tremorlabs/tremor/issues/454#issue-1707959713

### CODE REVIEW

**Comment by mitrotasios** [comment]
Do you maybe have a screenshot that illustrates the issue? :)

**Comment by amirhhashemi** [comment]
image

Notice the horizontal scrollbar at the bottom

You can reproduce it by adding a tooltip to an Icon with this text:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

**Comment by mitrotasios** [comment]
Hmm I would say it is the responsibility of the end user to avoid tooltips of that size. Setting a max width feels a bit hacky / restrictive, wdyt?

**Comment by amirhhashemi** [comment]
I think the library should be prepared for long tooltips. It may not be very popular but sometimes it's needed. 

Another question is how much is too long? A small text on desktop might be too long for mobile and if we don't limit the width, mobile users will potentially experience the bug. So I think it's better to be handled on the Tremor side. 

I also checked the Tooltip component of Chakra-UI and they also limit the tooltip width: https://github.com/chakra-ui/chakra-ui/blob/38acfe89c5d1f1edc67bbc44e2edd38980ca3e08/packages/components/theme/src/components/tooltip.ts#LL24C10-L24C10

**Comment by amirhhashemi** [comment]
It also makes tooltips look nicer and more readable in my opinion. Compare this:
image
With this:
image

**Comment by mitrotasios** [comment]
Fair point, agree!

**Review by mitrotasios — APPROVED** [review]
Thanks, LGTM 🥳

**Pull request merged**
