### PR TITLE
feat: Adds Animation properties to set timing

### LINKED ISSUE #421: feature: Add option to control the duration or speed of the animation in Area and other charts
When using the AreaChart, there is an option to turn on or off showing an animated rendering of the data points -- but it can feel a little slow, and give the impression that the performance is also sluggish.

I noticed that the charts wrap ReCharts and they have an option to set the `animationDuration`:

https://recharts.org/en-US/api/Area#animationDuration 

This is a request to include the `animationDuration` option and pass it to all the chart/containers to be babel to control the speed of the animation.

In fact, exposing (but defaulting to sensible values):

image

* animationBegin
* animationEnd
* animationEasing
* animationDuration

might be useful.

---

Oh, I just realized that they get passed as  `...other` so perhaps this issue is more of a documentation issue to say these properties are available, too.

See: https://www.tremor.so/docs/components/area-chart

Although I do get a warning:

image

---

Update:

Actually `other` is passed to the div, not the `ReChartsAreaChart` or `ResponsiveContainer`

### PR DESCRIPTION
**Pull request by dthyresson**
Note: After review, this PR just adds tech AnimationDuration (no events or other timings).

--- 
# What 

This PR adds properties to control animations.

It adds a new interface `BaseAnimationTimingProps` that contains:

```ts
interface BaseAnimationTimingProps extends React.HTMLAttributes<HTMLDivElement> {
  onAnimationStart?: () => void;
  onAnimationEnd?: () => void;
  animationBegin?: number;
  animationDuration?: number;
  animationEasing?: "ease" | "ease-in" | "ease-out" | "ease-in-out" | "linear";
  showAnimation?: boolean;
}
```

# Why

Fixes Fixes https://github.com/tremorlabs/tremor/issues/421

The begin, duration and easing options help control the behavior of the animation to speed it up, or slow it down from the default 1.5 seconds.

The on start and end handlers let you trigger a function when a data series animates or stops animating.

# How

Charts like Area, Line, Bar and Donut have these new options.

# Testing

Stories for each chart demonstrate these capabilities.

# Issues

Not sure if `BaseAnimationTimingProps` is the name you would prefer; as well as ordering of props in the components.

The on/end animation handlers trigger per data series, so if you have two lines in a LineChart each will fire.

I could not immediately see how to pass args to these handlers in ReCharts.

# Docs

Note: The documentation for each component will need to be updated to add each of these options.

### CODE REVIEW

**Comment by dthyresson** [comment]
@severinlandolt @mitrotasios any chance for a review?

**Comment by mitrotasios** [comment]
@dthyresson, sorry for the delay! We think it would be best to only add the `animationDuration` prop since the other props are too granular, for now, for Tremor's simple / opinionated API and would bloat the namespace, only to accommodate for very specific animation use cases. I hope that makes sense. Would you like to adjust the PR? Happy to do it myself otherwise 🙂

**Comment by dthyresson** [comment]
> @dthyresson, sorry for the delay! We think it would be best to only add the `animationDuration` prop since the other props are too granular, for now, for Tremor's simple / opinionated API and would bloat the namespace, only to accommodate for very specific animation use cases. I hope that makes sense. Would you like to adjust the PR? Happy to do it myself otherwise 🙂

Understood. But, do you mind if I keep the `animationEasing` as it does related to the "way" the animation animates (just as duration does) while the others are event hooks.?

**Comment by mitrotasios** [comment]
I think it wouldn't add a lot of value for now because the library is so opinionated. It feels inconsistent being so restricted in styling while offering various animation styles for only the charts at the same time. I wouldn't rule out adding it in the future though. I hope it makes sense and sorry for being so pedantic 😄 Its just that we prefer being conservative when adding props and avoiding breaking changes in the future.

**Comment by dthyresson** [comment]
> I think it wouldn't add a lot of value for now because the library is so opinionated. It feels inconsistent being so restricted in styling while offering various animation styles for only the charts at the same time. I wouldn't rule out adding it in the future though. I hope it makes sense and sorry for being so pedantic 😄 Its just that we prefer being conservative when adding props and avoiding breaking changes in the future.

No worries. Totally appreciate opinionated libraries. Will do.

**Comment by dthyresson** [comment]
@mitrotasios Finally got around to updating this PR to simply include the animationDuration and rebase with current main.

**Comment by mitrotasios** [comment]
awesome, thanks so much @dthyresson 🤗

**Review by mitrotasios — APPROVED** [review]
LGTM 🚀

**Pull request merged**
