### PR TITLE
feat: add pagination to the table

### LINKED ISSUE #283: How to add pagination to the table?
Is there a way to tremor to handle the pagination or do we need to handle it manually?

Awesome library, keep up the good work

### PR DESCRIPTION
**Pull request by gitstart**
FIxes: #283 
Demo: https://www.loom.com/share/0123cd4d132944ef8381f92d48c09916

What: Add pagination on Table component
Why: Because now is not possible set pagination
How: controlling the rendering of table rows with a custom hook
Testing: Run storybook and go to ListElements > Table

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
Hello @mitrotasios! Could you kindly review this PR, please?

**Comment by Luttik** [comment]
@gitstart good work. We'd also love a feature like this. Especially when it can delay the data-load. Maybe you can request a review in the top-right of the pr, instead of just tagging @mitrotasios in a comment.

**Comment by gitstart** [comment]
> @gitstart good work. We'd also love a feature like this. Especially when it can delay the data-load. Maybe you can request a review in the top-right of the pr, instead of just tagging @mitrotasios in a comment.

Hi @Luttik. This section is disabled it is not possible to ask for reviews there, that's the reason for the comments with tags, could you help us with that?

**Comment by Luttik** [comment]
I don't know how. I'm not part of the tremor team. Just looking for the same feature.

**Comment by rockse** [comment]
It will be great to get this in

**Comment by severinlandolt** [comment]
Heya! I am not convinced that a general pagination component makes sense within the table today.

Taken from the corresponding issue:

> A few thoughts:
> 
> * Would be it a "123 ... 789" or a "show more" component?
> * Should there be a page input field or just left/right buttons?
> * Adding a skip to the end/start button?
> 
> There are so many paths ideal pagination could look like. In light of this, I would leave it to the developer to create a pagination specifically tailored to the use case.
> 
> One more thing, adding pagination e.g. a property to specify defaultPageSize={n}, so that the table only displays n rows, and adding as many pages as needed. This would change the Table API significantly, basically reducing the table to one component because you have to take care of the pagination logic throughout the component.

We are still convinced that adding a general, paginated table won't be a good addition to the library. So I am going to close this PR. 

**Notes**
You can leverage the `Table` components for crafting intricate data tables. Integrate it with @tanstack/react-table for enhanced table functionalities such as sorting, filtering, and _pagination_. 
Addtionally, here's an example of a [simple pagination implementation](https://github.com/tremorlabs/tremor/issues/283#issuecomment-1558900212).

**Comment by Luttik** [comment]
@severinlandolt Maybe its an idea to have non-official components like this one in a different repo with a 2nd tier of support?

**Pull request closed without merging**
