### PR TITLE
feat: add selected text option to MultiSelectBox

### PR DESCRIPTION
**Pull request by Ehesp**
What - what changes are in this PR

Adds a new `selectedText` prop which shows custom text for the selected values.

Why - why are these changes relevant

It's useful to show a custom message, containing the selected values.

How - how have the changes been implemented

N/A

Testing - how has the changes been tested or how can the reviewer test the feature

Tested locally for now. Don't see many full component tests.

### CODE REVIEW

**Comment by mitrotasios** [comment]
@Ehesp thanks for the PR! Would you mind elaborating what kind of text you would like to add to the selection?

**Comment by Ehesp** [comment]
Well anything I want really. Showing "3 selected" isn't that useful in my UI. Instead I'd like to show what is selected using the values.

**Comment by mitrotasios** [comment]
In that case I think something like a list of clickable buttons would be useful. E.g. like this implementation:
image

Initially we wanted to go for this approach but it turns out to be quite tricky to design such a component fulfilling the responsive criteria for cases where there are many selections (same goes for a simple text input).

I think your point is very valid, but we wouldn't like to rush such decisions as we want to avoid breaking changes in the future. I hope you understand. We will try to figure out a suitable responsive solution and come back to your PR. We would also appreciate any input on this :)

**Comment by Ehesp** [comment]
That's fine, although this isn't a breaking change since its an optional prop.

But yeah appricate it needs to be considered.

**Comment by mitrotasios** [comment]
yeah, I mean a breaking change in the sense that we would need to deprecate that prop if we chose to go with another solution in the future :) Thanks for understanding!

**Comment by mitrotasios** [comment]
We will probably not go ahead with this feature at the moment. Sorry about that and thanks for the work!

**Pull request closed without merging**
