### PR TITLE
feat: enableClear option for SearchSelect component

### PR DESCRIPTION
**Pull request by sudhamjayanthi**
**Description**
Implemented the enableClear functionality in `SearchSelect` similar to `Search` component. 

**Related issue(s)**
https://github.com/tremorlabs/tremor/discussions/680#discussion-5631426 

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Screenshots (if appropriate):**
demo gif

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the related issue section above
- [x] My change requires a change to the documentation. (Managed by Tremor Team)
- [x] Check the ["Allow edits from maintainers" option](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) while creating your PR.
- [x] Add refs #XXX or fixes #XXX to the related issue section if your PR refers to or fixes an issue.
- [ ] I have added tests to cover my changes

PS: I needed this for my project, but thought it would be better to contribute for everyone else like me. Feel free to let me know if any changes are required :) Otherwise kindly merge it!

### CODE REVIEW

**Comment by sudhamjayanthi** [comment]
thanks for the changes @severinlandolt! can we merge this?

**Comment by severinlandolt** [comment]
Yes, will be included in the next minor version.

**Comment by severinlandolt** [comment]
Sorry, will make it into v3.9

**Comment by sudhamjayanthi** [comment]
hey @severinlandolt, do we have a estimated release date for v3.9?

**Comment by severinlandolt** [comment]
ca. mid October

**Pull request merged**
