### PR TITLE
feat: add Checkbox component

### LINKED ISSUE #456: Feature request: Checkbox component
A Checkbox component would be great. In my recent app I needed a checkbox for a few things:

- In the login page, there is a "Remember me" checkbox that if checked, makes the login session last longer.
- To on/off some user account settings
- I have a chart which shows a list of categories and the user can select/unselect the categories. In my case, it didn't make sense to use the `MultiSelectBox` component to show all the available categories, so I show them in a grid with a checkbox that toggles that category.

You can argue that all of them can be achieved with the `Toggle` component, but I think having a traditional `Checkbox` is a good thing because it takes less space and it's simpler. Also the value of Toggle can only be string but sometimes a boolean is needed.

I'm willing to prepare a PR for this, just let me know.

### PR DESCRIPTION
**Pull request by gitstart**
FIxes #456

What: Create a Checkbox component
Why: To be possible to add a Checkbox component using the tremor lib
How: The changes was implemented following the other component as a base, was created a new folder on input-element called CheckBox with this changes. Also was created a test file and a .stories file

Tests: 
image

Custom CheckBox example: 
image

## Testing
run:
```bash
npm run storybook
```
Search for CheckBox in "InputElements" folder

## Demo
Loom video with the changes using the created page component as example and with the component on storybook:
https://www.loom.com/share/136cc8da195a42ec84e1c2c6551da9c6

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
👋  Hello @mitrotasios! Can you review this PR, please?

**Comment by mitrotasios** [comment]
hey @gitstart thanks for the work! 🥳 I think we will release v3 before we will add any new components. V3 will be released in the next week probably, so I would review / merge this PR afterwards :)

**Comment by severinlandolt** [comment]
Hi, I am sorry but I have to say no to this. In the future, please submit PR's for new components only if they are explicitly described and assigned by one of the core maintainers. Usually labeled with "help wanted" or "good first issue", thank you :)

**Comment by Lary15** [comment]
Is this little guy in some beta release?

**Comment by severinlandolt** [comment]
Hi @Lary15, not yet but later this month.

**Comment by severinlandolt** [comment]
Updating Beta branch

**Review by christopherkindl — APPROVED** [review]

**Comment by kronos1345** [comment]
Hi @severinlandolt . When will it be released to main branch?

**Comment by severinlandolt** [comment]
Hey @kronos1345, is a breaking change so no earlier than v.4.0

**Pull request merged**
