### PR TITLE
feat: custom chart colors support

### LINKED ISSUE #80: Allow for custom colors
Hello, just wanted to say that this is an awesome project and l hope to use it in production. However, as other developers have mentioned, I don't think I'll be able to use this library until I have the ability to use custom colors defined in tailwind.config. This is purely for branding reasons of course. Is this feature currently on the roadmap? Or are you guys sticking to the strictly-opinionated model? Respect the decision either way.

### LINKED ISSUE #565: [Feature]: Support for custom hex colors
### What problem does this feature solve?

I would like to know if there is any possibility of supporting custom hex colors for theming the components, such as defining primary, secondary, tertiary and so on... colors.

Thanks in advance,

Regards,

Borja

### What does the proposed API look like?

_No response_

### PR DESCRIPTION
**Pull request by adamhenson**
**Description**

As described in #565, chart colors are limited to [base colors typed as `Color`](https://github.com/tremorlabs/tremor/blob/1744e4dda4562d17e74947c5e2804578677177ed/src/lib/inputTypes.ts#L35-L58).

For example, this chart will render line colors as expected.

```tsx
<LineChart {...props} colors={["emerald", "indigo"]} />
```

But, this will not work.

```tsx
<LineChart {...props} colors={["#32a852", "custom-color-100"]} />
```

This limitation seems to be due to the complexity in which `className`s are generated under the hood (dynamically at run time and statically at build time via Tailwind theme `safelist`). See [getColorClassNames](https://github.com/tremorlabs/tremor/blob/1744e4dda4562d17e74947c5e2804578677177ed/src/lib/utils.tsx#L73-L107).

**Changes**

This change introduces a new optional `customChartColors` `prop` on chart components to support custom colors (including hex or custom theme colors) on the following components.

- `AreaChart`
- `BarChart`
- `DonutChart`
- `LineChart`
- `ScatterChart`
- `SparkAreaChart`
- `SparkBarChart`
- `SparkLineChart`

Implementation example below.

```tsx
<LineChart {...props} customChartColors={["#32a852", "custom-color-100"]} />
```

The caveat here is that such implementation would require an update to the Tailwind theme `safelist` to ensure Tailwind generates `className`s at build time to mirror `className`s calculated at run time in functions like [getColorClassNames](https://github.com/tremorlabs/tremor/blob/1744e4dda4562d17e74947c5e2804578677177ed/src/lib/utils.tsx#L73-L107). This caveat is somewhat pre-existing, with the reliance on `safelist`. My thought was that we could add a new section to [the theming docs](https://www.tremor.so/docs/getting-started/theming) if using `customChartColors`. Please let me know if I can help here.

Example `safelist` to support the above implementation:

```typescript
safelist: [
  // ..
  // ..
  // custom colors
  ...["[#32a852]", "[#fcba03]"].flatMap((customColor) => [
    `bg-${customColor}`,
    `border-${customColor}`,
    `hover:bg-${customColor}`,
    `hover:border-${customColor}`,
    `hover:text-${customColor}`,
    `fill-${customColor}`,
    `ring-${customColor}`,
    `stroke-${customColor}`,
    `text-${customColor}`,
    `ui-selected:bg-${customColor}]`,
    `ui-selected:border-${customColor}]`,
    `ui-selected:text-${customColor}`,
  ]),
],
```

**Related issue(s)**

- Closes #565 
- Closes #80 
- Related #640 

**What kind of change does this PR introduce?**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**How has This been tested?**

Storybook stories have been added for all components with the new `customChartColors` `prop`.

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the related issue section above
- [x] My change requires a change to the documentation. (Managed by Tremor Team)
- [x] I have added tests to cover my changes
- [x] Check the ["Allow edits from maintainers" option](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) while creating your PR.
- [x] Add refs #XXX or fixes #XXX to the related issue section if your PR refers to or fixes an issue.
- [x] By contributing to Tremor, you confirm that you have read and agreed to Tremor's [CONTRIBUTING.md](https://github.com/tremorlabs/tremor/blob/main/CONTRIBUTING.md) guideline. You also agree that your contributions will be licensed under the [Apache License 2.0](https://github.com/tremorlabs/tremor/blob/main/License) license.

### CODE REVIEW

**Comment by severinlandolt** [comment]
Oh wow, what an amazing PR! 🤩 I am a big fan of your implementation details and thank you for the thorough description. 

My thoughts on `safelist`: Not a big concern in my view, given the usefulness of the feature. (Note: #484 also facilitates an adjustment to the config, should be released together)

Will take a look later today and thank you very much for your work!

**Comment by adamhenson** [comment]
Thanks so much @severinlandolt 🙏 and I agree about `safelist`. Also thanks for fixing the lint issue!

**Comment by severinlandolt** [comment]
@adamhenson 

```npm i @tremor/react@3.12.0-beta.1```
https://tremor-so-git-feat-312-tremor.vercel.app/changelog

**Comment by adamhenson** [comment]
Awesome, thanks so much for the quick help on this one @severinlandolt. Appreciate this project 🙏

**Comment by severinlandolt** [comment]
Hey @adamhenson, we were discussing the following:

Integrate the `customChartColors` logic into the color prop.
→ Include a hint in the documentation indicating that the color prop on the charts also supports custom values.

What do you think? And would you have the time to create another PR with those changes?

**Comment by adamhenson** [comment]
Hi @severinlandolt - yes, that makes sense to me. I was thinking about that route too as eventually I think I'd want to be able to use custom colors in more than just these charts. My only concern would be around programmatically determining if a `color/s` `prop` has a custom color or not. In my change, I was able to hook into color className generation everywhere by knowing if we're dealing with a custom color via the explicit `customChartColors` `prop`.

I can definitely take a deeper dive and see what I can do. I'm pretty busy this week, but if I don't get to it this week, I can probably spend some time on this next weekend.

**Comment by severinlandolt** [comment]
That would be great @adamhenson! Feel free to branch off from [`beta`](https://github.com/tremorlabs/tremor/tree/beta) it's the most up to date branch.

**Comment by adamhenson** [comment]
Hey @severinlandolt - if I can pull this off, I'm assuming I should remove `customChartColors` in the same PR - correct?

**Comment by severinlandolt** [comment]
@adamhenson Yes, that would be awesome!

**Comment by adamhenson** [comment]
Okay, I believe #843 is what you're after @severinlandolt to "Integrate the customChartColors logic into the color prop".

**Comment by Mxs2019** [comment]
Was this ever released? I need the ability to use custom hex colors at run time since they aren't known at generator time. Is there any way to do that?

**Pull request merged**
