### PR TITLE
feat: Tooltip for Buttons

### LINKED ISSUE #471: Enhancement Request: Tooltip for buttons
**What** - I would like to request a `tooltip` prop for the `Button` component, which behaves the same way `tooltip` behaves on `Icon` and `Badge`.

**Why** - I would like to explain to users why buttons are disabled with a hover tooltip.

### PR DESCRIPTION
**Pull request by gitstart**
Fixes: https://github.com/tremorlabs/tremor/issues/471
What: Add the possibility to use tooltips on button component
Why: To be able to use tooltips in this component
How: The changes was implemented following the components `src/components/icon-elements/Icon/Icon.tsx` and `src/components/icon-elements/Badge/Badge.tsx`, they already have a tooltip component

## Testing
run:
```bash
npm run storybook
```

1. Go to InputElement/Button/Sizes
2. Hover over the first column buttons

## Demo

Loom Video: https://www.loom.com/share/5181bda86a65435b8f6298ba92dfb493

---

This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
:wave: Hello @mitrotasios!  Can you review this PR, please?

**Comment by gitstart** [comment]
:wave: Hello @mitrotasios! Can you review this PR, please?

**Review by mitrotasios — CHANGES_REQUESTED** [review]
Great job! Would it be possible to add a small delay to the tooltip (e.g. 150-300ms)? I think this is better for tooltips on buttons. :)

**Comment by gitstart** [comment]
> Great job! Would it be possible to add a small delay to the tooltip (e.g. 150-300ms)? I think this is better for tooltips on buttons. :)

we will work on it and get back to you soon.

**Comment by gitstart** [comment]
Hello @mitrotasios 
Changes have been made, you can see a tooltip speed difference on an icon and a button, in the video in the description

**Review by mitrotasios — APPROVED** [review]
LGTM!

**Comment by abdullah-txfusion** [comment]
Seems like there's no straightforward way to style the tooltip

**Pull request merged**
