### PR TITLE
feat: multiple y axes

### PR DESCRIPTION
**Pull request by scaltunsoy**
**Description**

I am opening this PR because https://github.com/tremorlabs/tremor/pull/857 was closed. @severinlandolt asked me to open a new PR (https://github.com/tremorlabs/tremor/pull/857#issuecomment-2067227546).

**Related issue(s)**

https://github.com/tremorlabs/tremor/issues/855
https://github.com/tremorlabs/tremor/issues/827

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] New Feature (BREAKING CHANGE which adds functionality)
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**How has This been tested?**

Storybook. 4 new stories has been added in total.

**Screenshots (if appropriate):**

Multiple y axes:
image

Y axis on the right side:
image

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the related issue section above
- [x] My change requires a change to the documentation. (Managed by Tremor Team)
- [x] I have added tests to cover my changes
- [x] Check the ["Allow edits from maintainers" option](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) while creating your PR.
- [x] Add refs #XXX or fixes #XXX to the related issue section if your PR refers to or fixes an issue.
- [x] By contributing to Tremor, you confirm that you have read and agreed to Tremor's [CONTRIBUTING.md](https://github.com/tremorlabs/tremor/blob/main/CONTRIBUTING.md) guideline. You also agree that your contributions will be licensed under the [Apache License 2.0](https://github.com/tremorlabs/tremor/blob/main/License) license.

### CODE REVIEW

**Comment by severinlandolt** [comment]
Hi! Sorry for the delayed response. I already forked your repo and made a new PR with correct attribution. Here is the beta branch: https://github.com/tremorlabs/tremor/tree/beta-dual-axis

We currently have a few users testing it out. Will give it some time because it's a significant change.

**Comment by jbergstroem** [comment]
@severinlandolt any update on how testing is progressing? Thanks in advance.

**Comment by sk-** [comment]
@severinlandolt was there any reason for closing this PR? Were there any fundamental issues found while testing?

**Comment by severinlandolt** [comment]
Hi @sk-,

The answer to your question is yes.

Our test users reported that it didn’t feel right having multiple axes on the **same** chart type. When you have multiple lines in a chart, it's almost impossible to guess which line corresponds to which axis, and the same issue arises with bars.

We decided to take a different approach by introducing a new chart type: [ComboChart](https://tremor.so/docs/visualizations/combo-chart).

It has been released as a copy-and-paste component, and we are currently gathering feedback. We plan to add this to the package later.

**Pull request closed without merging**
