### PR TITLE
feat: allow axis customization on charts

### LINKED ISSUE #394: Allow y-axis customizaion
## Issue
- Cannot format y-axis to be currency, since providing string seems to always add decimal point.

## Solution
  I think allowing some of the props like disabling decimal on y-axis would help in situations like this.

### PR DESCRIPTION
**Pull request by priosshrsth**
* Resolves #394

Add optoinal yAxisConfig and xAxisConfig options to BaseChartProps.
Currently, we can only provide allowDecimal option as these configs.

### CODE REVIEW

**Comment by mitrotasios** [comment]
@priosshrsth, thanks for the work. I think it wouldn't be a good idea to expose the entire Axis config (at least for now). Its probably better to use recharts directly if full customisation is required. 

Maybe my answer in your issue (#394) fixes your problem?

**Comment by priosshrsth** [comment]
@mitrotasios Should I have just enabled the `allowDecimals` options then? If so, I can update the PR. I thought I would just restrict it by type and if someone wants to customize still, they why not? But, if  not, I think I will use the recharts directly like you mentioned.

**Comment by mitrotasios** [comment]
yup, that would be great!

**Comment by priosshrsth** [comment]
@mitrotasios I have updated the PR. But I was confused if to expose the option under yAxisConfig or the main props for the components. So, I did not make the change on that part.

**Comment by mitrotasios** [comment]
@priosshrsth, I think its better to not have an axisConfig and add the `allowDecimals` prop on the top-level namespace of the component which will then only be propagated to the yAxis.

**Comment by priosshrsth** [comment]
@mitrotasios Thanks for your feedbacks. I have updated the PR accordingly. But looks like I was wrong about this. The charts now do not have decimal points, after removing 2nd parameter from formatter.
My previous code for currencyFormatter was as 
```ts
const formatter = (
  { locales = "en-US", ...options } = {} as Intl.NumberFormatOptions & {
    locales?: string;
  }
) => {
  return new Intl.NumberFormat(locales || "en-US", {
    ...defaultOptions,
    ...options,
  });
};

export const numberToCurrency = (number: number, displayCents = false) => {
  return formatter({    
    maximumFractionDigits: displayCents ? 2 : 0,
  }).format(number);
};
```

Now, after creating 2 separate function to format the currency with or without cents and removing the use of 2nd parameter, everything is working fine. My guess is rechart provides multiple parameters to formatter, but I could not find anything on the doc.

**Comment by mitrotasios** [comment]
thanks for the update @priosshrsth, does that mean everything works fine now?

**Comment by priosshrsth** [comment]
Yes, everything is working fine.

**Comment by mitrotasios** [comment]
Awesome! If thats the case I would close the PR.

**Pull request closed without merging**
