### PR TITLE
feat: click event for linechart and donut chart

### LINKED ISSUE #195: onClick Handler on Tremor Charts
I just checked the documentation and browsed the Tremor github is there a documented way to add a onClick Handler on the tremor charts?

I saw that they are based on Recharts and Recharts has already implemented such an API for there charts. 
https://recharts.org/en-US/examples/BarChartWithCustomizedEvent
https://recharts.org/en-US/api/BarChart

This is not yet implemented for Tremor rght?

### PR DESCRIPTION
**Pull request by jzfrank**
**Description**
onClick event handle for LineChart.

Note this PR is still work in progress. And there are several points worth mentioning: 

- The style of customized dots style needs the expertise of Tremor maintainers
- Currently, I comment out the `content` field of `Legend`, because it will mask the onClick event provided by `Legend` of recharts. We have two ways to proceed: either refactor our `ChartLegend` and `LegendItem` so that it could respond `onClick` properly (recommended), or we could degrade to vanilla recharts `Legend` and style it better. 

**Related issue(s)**
https://github.com/tremorlabs/tremor/issues/195 

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**How has This been tested?**
storybook

**Screenshots (if appropriate):**

**The PR fulfills these requirements:**

- [ ] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the related issue section above
- [ ] My change requires a change to the documentation. (Managed by Tremor Team)
- [ ] I have added tests to cover my changes
- [x] Check the ["Allow edits from maintainers" option](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) while creating your PR.
- [x] Add refs #XXX or fixes #XXX to the related issue section if your PR refers to or fixes an issue.
- [ ] By contributing to Tremor, you confirm that you have read and agreed to Tremor's [CONTRIBUTING.md](https://github.com/tremorlabs/tremor/blob/main/CONTRIBUTING.md) guideline. You also agree that your contributions will be licensed under the [Apache License 2.0](https://github.com/tremorlabs/tremor/blob/main/License) license.

### CODE REVIEW

**Comment by christopherkindl** [comment]
Thanks for the draft @jzfrank! We will review it asap.

**Comment by severinlandolt** [comment]
Hi @jzfrank! Thanks for the swift response. I'm really impressed with the first version of the chart; it aligns well with our desired direction.

I've made a commit where I added an onValueChange prop, which will return the payload when an item is clicked.

* `Legend:` I would go with your recommendation and refactor the `ChartLegend` and `LegendItem`. Happy to take a suggestion from you.
* `Dot` Opacity: Currently, the customized dot inherits the opacity of the line (opacity-30). The dot should have an opacity of 100% i.e. should not be affected by the opacity of the line. 
* `Dot` Styling: Should have the same styling as `activeDot`
* `enableOnClick`: The onClick functionality should be optional. Ideally with a enableOnClick?: boolean with default true. I will take this to the community to evaluate a good design/naming for that.

Please let me know if you have further questions. You're welcome to make any adjustments to what I've committed.

**Comment by severinlandolt** [comment]
Hi @jzfrank! Thanks for the swift response. I'm really impressed with the first version of the chart; it aligns well with our desired direction.

I've made a commit where I added an onValueChange prop, which will return the payload when an item is clicked.

* `Legend:` I would go with your recommendation and refactor the `ChartLegend` and `LegendItem`. Happy to take a suggestion from you.
* `Dot` Opacity: Currently, the customized dot inherits the opacity of the line (opacity-30). The dot should have an opacity of 100% i.e. should not be affected by the opacity of the line. 
* `Dot` Styling: Should have the same styling as `activeDot`

Please let me know if you have further questions. You're welcome to make any adjustments to what I've committed.

**Comment by jzfrank** [comment]
Hi @christopherkindl and @severinlandolt ! Thanks a lot for the quick review and thanks for assuming the burden of fine tuning styles :)
Let me know if you need other assistance!

**Comment by jzfrank** [comment]
As discussed, I have refactored the `ChartLegend` and `LegendItem` so that click event on legend item could be listened. 
Now, the remaining thing would be to fine tuning the styles. I'm still working on that, but many thanks if anyone wants to give a help hand!

**Comment by mbauchet** [comment]
> As discussed, I have refactored the `ChartLegend` and `LegendItem` so that click event on legend item could be listened. Now, the remaining thing would be to fine tuning the styles. I'm still working on that, but many thanks if anyone wants to give a help hand!

I can help if needed

**Comment by jzfrank** [comment]
> > As discussed, I have refactored the `ChartLegend` and `LegendItem` so that click event on legend item could be listened. Now, the remaining thing would be to fine tuning the styles. I'm still working on that, but many thanks if anyone wants to give a help hand!
> 
> 
> 
> I can help if needed 

Great, please go ahead 😉 Thanks a lot! @mbauchet

**Comment by mbauchet** [comment]
Hi @jzfrank, just fixed the clicked dot style, but I don't have permission to push on your repo
Also, I'm not sure how useful the hasClickedPoint state really is

**Comment by jzfrank** [comment]
> Hi @jzfrank, just fixed the clicked dot style, but I don't have permission to push on your repo Also, I'm not sure how useful the hasClickedPoint state really is

Hi @mbauchet , thanks for the help. I have invited you as collaborator. 
I used hasClickedPoint to monitor if a point is clicked. Feel free to refactor it.

**Review by severinlandolt — APPROVED** [review]

**Pull request merged**
