### PR TITLE
build: postcss upgrade for storybook

### LINKED ISSUE #172: Storybook requires postcss 8
I'm not able to start storybook without upgrading to and using postcss 8. Will post a fix (according to [this](https://storybook.js.org/addons/@storybook/addon-postcss) guide).

### PR DESCRIPTION
**Pull request by jelleag**
Used this (https://storybook.js.org/addons/@storybook/addon-postcss) guide to enforce storybook to use postcss8, as required by PostCSS plugin tailwindcss.
Fixes #172

### CODE REVIEW

**Comment by mitrotasios** [comment]
Thanks for the PR!

**Review by mitrotasios — APPROVED** [review]

**Comment by mitrotasios** [comment]
The release ci pipeline failed when the dependencies were installed (even though the build pipelines succeeded for some reason), so I needed to revert. Will take another look at it

**Comment by mitrotasios** [comment]
can you please re-open the PR once you have time? :)

**Comment by jelleag** [comment]
Done!

**Pull request merged**
