### PR TITLE
feat: adding a year selector to datepicker

### PR DESCRIPTION
**Pull request by jelleag**
Solving issue #116

### CODE REVIEW

**Comment by jelleag** [comment]
Accidentally included commit [f71e251](https://github.com/tremorlabs/tremor/pull/183/commits/f71e2516dcc45e4b8360adda5c1c7e7c1b619bf4), apologies.

**Comment by eykrehbein** [comment]
Love that, @jelleag! One thing I found while testing it:
The month selector buttons are aligned relative to the text in the middle, while the year selectors are always fixed outside. That causes the margins between month-selector-buttons and year-selector-buttons to vary based on the length of the name of the currently selected month.
It's a small thing, but maybe you can fix it easily :) Happy coding!

CleanShot 2022-11-12 at 09 09 39
Bigger margins:
CleanShot 2022-11-12 at 09 09 35

**Comment by christopherkindl** [comment]
Many thanks @jelleag and @eykrehbein for this lovely discussion and contribution. We are working hard on release v1.2.0 right now. We just decided to consider year selection in this upcoming release and will use this PR as the base. Will probably adjust the styling a little bit.

Many thanks for this again! 🙏 😍

**Comment by mitrotasios** [comment]
Sorry for the many commits, we messed up the branches a bit.. Thanks for the awesome PR!

**Pull request merged**
