### PR TITLE
feat: add number input and email/url types to text input

### LINKED ISSUE #329: Feature Enhancement: Text Input to extend to email, password and number types
Are there any plans to extend the Text Input component to support other text types viz: email, passwords and numbers? Thanks

### PR DESCRIPTION
**Pull request by gitstart**
Fixes: https://github.com/tremorlabs/tremor/issues/329

What - Add ability to set input type to email/url and added new NumberInput
Why - Because it is currently not possible to set a input to type email,number or url
How - Adding a new type prop with email/url types and creating a new NumberInput component
Testing - You can see the changes by running Storybook and choosing the "InputElements> TextInput/NumberInput" option

## Demo
https://www.loom.com/share/e5a46921a3714b3a9b01cf7bea266ce3

### CODE REVIEW

**Comment by gitstart** [comment]
:wave: Hello @mitrotasios! Can you review this PR, please?

**Comment by mitrotasios** [comment]
@gitstart thanks a lot for the work! Ideally we'd like the number input to look like this:
image

and support the following props:
* a `step` prop (i.e. 1, 0.1, 0.01)
* a `min` and `max` prop

**Comment by christopherkindl** [comment]
Hi @gitstart, how is it going with the number? Let us know if you need any help? :)

**Comment by gitstart** [comment]
> Hi @gitstart, how is it going with the number? Let us know if you need any help? :)

Hi @christopherkindl, sorry for the delay. We are working on the requested changes and will push an update soon.

**Comment by gitstart** [comment]
Hello @mitrotasios and @christopherkindl 
We've updated the `NumberInput` interface, but we've also made a change to the `onChange` logic. Here is the explanation:

By adding the arrows to increment and decrement the value, we will have two sources of change, when the user types, and when the user clicks the arrows. React knows how to handle changes by typing, but not with changes by arrows, even though HTML has methods for that: `stepDown()` and `.stepUp()`, React ignores them and doesn't fire the `onChange` event, even that the value of the input is changed. This means that we cannot trigger the `onChange` event in the same way that react does when the user types.

For this reason, we pass the numerical value directly as the first parameter, instead of the event, the event will only be sent when possible, which is when the user types it. When he uses the arrows, we only send the numerical value.

What do you think about it?

**Comment by gitstart** [comment]
Also, we are using the icons available in the project, and they are not the same as the image provided by you. What can we do about it? Can we add new icons? It would be really cool if you could provide us with these icons present in the image.

**Comment by mitrotasios** [comment]
thanks a lot for the work! Regarding your question, thats a good point. My suggestion is:
- We add an `onValueChange: (value: number) => void` event that is triggered either when a user types or when the arrows are clicked (users should only permitted to type in numerical characters)
- We add an optional `onSubmit: (value: number) => void` event, that is triggered when a user presses `enter`

wdyt?

**Comment by gitstart** [comment]
@mitrotasios
Great, we'll work on it and send it as soon as possible. Thank you.

**Comment by gitstart** [comment]
Hello @mitrotasios 
The changes have been made, can you review them please?

**Comment by severinlandolt** [comment]
Hi @gitstart, thank you for incorporating the changes. There are a few things left that need some polishing, I will list them here:
1. Disabled State: Despite being disabled, I am still able to use the increase/decrease buttons. This should be disabled as well, see this video: https://github.com/tremorlabs/tremor/assets/41927988/7f57232b-afab-4255-b6aa-a935a5f09e49
2. The line of the buttons goes not all the way through. Please refer to the screenshot here: https://github.com/tremorlabs/tremor/pull/519#issuecomment-1616259961
CleanShot 2023-07-15 at 17 01 02@2x
3. The state with "error message" has a breaking design with the buttons. Ideally, the error message occurs on the left side of the buttons.
CleanShot 2023-07-15 at 17 01 02@2x

Please feel free to reach out if anything is unclear!

**Comment by gitstart** [comment]
Hello @severinlandolt, the changes to solve the problems you listed have been sent, can you review them?

**Comment by severinlandolt** [comment]
Hi @gitstart, thanks for making the according changes, looks good to me. In my review, I found two other things that need a slight adjustment.

1. The arrows have a slightly different color here:
CleanShot 2023-07-17 at 11 27 05@2x

It should follow the same styling as the buttons in the Date (Range) Picker:

Default arrow color: `text-tremor-content-subtle`
→  When hovered: `text-tremor-content`

2. Only the arrow icons act as the button (on click). The whole area should be considered a button. 
image

**Comment by gitstart** [comment]
Hello @severinlandolt :wave: 
The code has been updated, can you review the new changes?

**Comment by severinlandolt** [comment]
Hey @gitstart, I do not think that the desired changes have been correctly implemented


1. The arrows still have a different color and do not change their color upon hover. 
CleanShot 2023-07-18 at 13 20 39@2x

2. It it's only by clicking the arrow that the number changes. The whole button surrounding the arrow should change the number.

https://github.com/tremorlabs/tremor/assets/41927988/393bae1e-f573-48e9-b438-43752ac56233

**Comment by gitstart** [comment]
Hello @severinlandolt 
This is a little strange, here we can see the effects of the changes:
https://www.loom.com/share/44b1b750ae064e6abb2a6ef1fc983546

**Pull request merged**
